resultsdb/controllers/api_v1.py
# Copyright 2013, Red Hat, Inc
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Authors:
#   Josef Skladanka <jskladan@redhat.com>

import datetime
import re
from functools import partial

from flask import Blueprint, jsonify, request, url_for, abort
from flask.ext.restful import reqparse

from sqlalchemy.orm import exc as orm_exc
from sqlalchemy import exc as sqlalchemy_exc
from werkzeug.exceptions import HTTPException


# removed in flask 0.10 from flask.exceptions import JSONBadRequest
from werkzeug.exceptions import BadRequest as JSONBadRequest

import iso8601

from resultsdb import app, db
from resultsdb.serializers.api_v1 import Serializer
from resultsdb.models.results import Job, Result, Testcase, ResultData
from resultsdb.models.results import JOB_STATUS, RESULT_OUTCOME

QUERY_LIMIT = 20

api = Blueprint('api_v1', __name__)

##TODO: find out why error handler works for 404 but not fot 400

@app.errorhandler(400)
def bad_request(error):
    return jsonify({"message": "Bad request"}), 400


@app.errorhandler(404)
def not_found(error):
    return jsonify({"message": "Not found"}), 404

# =============================================================================
#                               GLOBAL VARIABLES
# =============================================================================

RE_PAGE = re.compile(r"([?&])page=([0-9]+)")

# RP contains request parsers (reqparse.RequestParser).
#    Parsers are added in each 'resource section' for better readability
RP = {}

# Serializer and URI helper to generate urls for resources
def __get_uri(o):
    cls = o.__class__.__name__

    if cls == 'Job':
        return url_for('api_v1.get_job', job_id = o.id, _external = True)
    if cls == 'Testcase':
        return url_for('api_v1.get_testcase', testcase_name = o.name, _external = True)
    if cls == 'Result':
        return url_for('api_v1.get_result', result_id = o.id, _external = True)

__serializer = Serializer(__get_uri)
SERIALIZE = __serializer.serialize

# =============================================================================
#                               GLOBAL METHODS
# =============================================================================

def pagination(q, page, limit):
    # pagination offset
    try:
        page = int(page)
        if page > 0:
            offset = page * limit
            q = q.offset(offset)
    except (TypeError, ValueError):
        pass

    # apply the query limit
    try:
        limit = int(limit)
    except (ValueError, TypeError):
        limit = QUERY_LIMIT

    q = q.limit(limit)
    return q

#TODO: find a better way to do this
def prev_next_urls():
    global RE_PAGE
    try:
        match = RE_PAGE.findall(request.url)
        flag, page = match[0][0], int(match[0][1])
    except IndexError: #page not found
        if '?' in request.url:
            return None, "%s&page=1" % request.url
        else:
            return None, "%s?page=1" % request.url

    prev = None
    next = None
    prevpage = page - 1
    nextpage = page + 1

    if page > 0:
        prev = RE_PAGE.sub("%spage=%s" % (flag, prevpage), request.url)
    next = RE_PAGE.sub("%spage=%s" % (flag, nextpage), request.url)

    return prev, next



def parse_since(since):
    since_start = None
    since_end = None
    if since is not None:
        # Add time information, as iso8601 can not deal with just date
        #   if time is provided, this won't change anything
        s = ['%sT00:00:00' % x.strip() for x in since.split(',')]
        try:
            since_start = iso8601.parse_date(s[0])
        except (TypeError, ValueError, iso8601.iso8601.ParseError): # Yes, this library sucks in Exception handling..
            raise iso8601.iso8601.ParseError()
        try:
            since_end = iso8601.parse_date(s[1])
        except IndexError: # since contained just one datetime
             pass
        except (TypeError, ValueError, iso8601.iso8601.ParseError): # Yes, this library sucks in Exception handling..
            raise iso8601.iso8601.ParseError()
    return since_start, since_end


def select_jobs(since_start = None, since_end = None, status = None, name = None):
    q = db.session.query(Job)

    # Time constraints
    if since_start is not None:
        q = q.filter(Job.start_time >= since_start)
    if since_end is not None:
        q = q.filter(Job.start_time <= since_end)

    # Filter by status
    if status is not None:
        q = q.filter(Job.status.in_([o.strip().upper() for o in args['status'].split(',')]))

    # Filter by name
    if name is not None:
        q = q.filter(Job.name.like('%%%s%%' % name))

    q = q.order_by(db.desc(Job.start_time == None), db.desc(Job.start_time))

    return q

def select_results(since_start = None, since_end = None, outcome = None, since_source = None, job_id = None, testcase_name = None, result_data = None):
    q = db.session.query(Result)

    # Time constraints

    # TODO: Find a way to do this 'better' without multiple (aka aliased) joins
    # Time constraints (args['since']) and ordering by Job.startt_time
    if since_start or since_end:
        if asince_source == 'job':
            if since_start and since_end:
                q = q.join(Job).order_by(db.desc(Job.start_time)).filter(Job.start_time >= since_start, Job.start_time <= since_end)
            else: #means "just since_start"
                q = q.join(Job).order_by(db.desc(Job.start_time)).filter(Job.start_time >= since_start)
        else:
            if since_start and since_end:
                q = q.order_by(db.desc(Result.submit_time)).filter(Result.submit_time >= since_start, Result.submit_time <= since_end)
            else: #means "just since_start"
                q = q.order_by(db.desc(Result.submit_time)).filter(Result.submit_time >= since_start)

    else:
        if since_source == 'job':
            q = q.join(Job).order_by(db.desc(Job.start_time))
        else:
            q = q.order_by(db.desc(Result.submit_time))

    # Filter by outcome
    if outcome is not None:
        q = q.filter(Result.outcome.in_([o.strip().upper() for o in outcome.split(',')]))

    # Filter by job_id
    if job_id is not None:
        q = q.filter(Result.job_id == job_id)

    # Filter by testcase_name
    if testcase_name is not None:
        alias = db.aliased(Testcase)
        q = q.join(alias).filter(alias.name == testcase_name)

    # Filter by result_data
    if result_data is not None:
        for key, values in result_data.iteritems():
            try:
                key, modifier = key.split(':')
            except ValueError: #no : in key
                key, modifier = (key, None)

            if modifier == 'like':
                alias = db.aliased(ResultData)
                if len(values) > 1: #multiple values
                    likes = []
                    # create the (value LIKE foo OR value LIKE bar OR ...) part
                    for value in values:
                        likes.append(alias.value.like(value))
                    # put it together to (key = key AND (value LIKE foo OR value LIKE bar OR ...))
                    q = q.join(alias).filter(db.and_(alias.key == key, db.or_(*likes)))
                else:
                    q = q.join(alias).filter(db.and_(alias.key == key, alias.value.like(values[0])))

            else:
                alias = db.aliased(ResultData)
                q = q.join(alias).filter(db.and_(alias.key == key, alias.value.in_(values)))

    return q


# =============================================================================
#                                      JOBS
# =============================================================================

RP['get_jobs'] = reqparse.RequestParser()
RP['get_jobs'].add_argument('page', default = 0, type = int, location = 'args')
RP['get_jobs'].add_argument('limit', default = QUERY_LIMIT, type = int, location = 'args')
RP['get_jobs'].add_argument('since', default = None, type = str, location = 'args')
RP['get_jobs'].add_argument('status', default = None, type = str, location = 'args')
RP['get_jobs'].add_argument('name', default = None, type = str, location = 'args')
RP['get_jobs'].add_argument('load_results', default = False, type = bool, location = 'args')


RP['create_job'] = reqparse.RequestParser()
RP['create_job'].add_argument('ref_url', type = str, required = True, location = 'json')
RP['create_job'].add_argument('status', type = str, default = 'SCHEDULED', location = 'json')
RP['create_job'].add_argument('name', type = str, default = None, location = 'json')

RP['update_job'] = reqparse.RequestParser()
RP['update_job'].add_argument('status', type = str, required = True, location = 'json')


@api.route('/v1.0/jobs', methods = ['GET'])
def get_jobs(): #page = None, limit = QUERY_LIMIT):
    try:
        args = RP['get_jobs'].parse_args()
    except JSONBadRequest as error:
        return jsonify({"message": "Malformed JSON data"}), error.code
    except HTTPException as error:
       return jsonify(error.data), error.code

    try:
        s, e = parse_since(args['since'])
    except iso8601.iso8601.ParseError:
        return jsonify({"message": "'since' parameter not in ISO8601 format"}), 400


    q = select_jobs(since_start = s, since_end = e, status = args['status'], name = args['name'])

resultsdb/templates/_formhelpers.html
{% macro render_field(field) %}
  <th>{{ field.label }}</th>
  <td>{{ field(**kwargs)|safe }}</td>
  <td>
    {% for error in field.errors %}
       <span style="color: red;">{{error}}</span>
    {% endfor %}
  </td>
{% endmacro %}

<!-- inspired by https://gist.github.com/maximebf/3986659 -->
{% macro form_field(field) %}
    {% set with_label = kwargs.pop('with_label', False) %}

    {% set inline_ = '' %}
    {% if field.type  == 'BooleanField' %}
        <div class="checkbox">
          <label>
            {{ field(**kwargs) }}
            {{ field.label.text|safe }}
          </label>
        </div>


    {% elif field.type == 'RadioField' %}
      {% for subfield in field %}
        <div class="radio">
          <label>
            {{ subfield(**kwargs) }}
            {{ subfield.label.text|safe }}
          </label>
        </div>
      {% endfor %}
    {% else %}
        <div class="form-group {% if field.errors %}has-error{% endif %}">
            {% set placeholder = '' %}
            {% if not with_label %}
                {% set placeholder = field.label.text %}
            {% endif %}

            {% if with_label %}
                <label for="{{ field.id }}">
                    {{ field.label.text }}{% if field.flags.required %} *{% endif %}:
                </label>
            {% endif %}

            {% set class_ = 'form-control' %}
            {% if field.type == 'FileField' %}
                {% set class_ = class_ + ' input-file' %}
            {% endif %}

            {{ field(class_=class_, placeholder=placeholder, **kwargs) }}

            {% if field.errors %}
                <span class="help-block">{{ field.errors|join(', ') }}</span>
            {% endif %}

            {% if field.description %}
                <p class="help-block">{{ field.description|safe }}</p>
            {% endif %}
        </div>
    {% endif %}
{% endmacro %}

resultsdb/templates/index.html
{% extends "layout.html" %}

{% block body %}

API documentation can be found <a href="http://docs.resultsdb.apiary.io/">here</a>.

{% endblock %}

resultsdb/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>{{ title|default('ResultsDB') }}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- Bootstrap -->
      <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
  </head>

  <body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="navbar-brand"><b>ResultsDB</b></span>
        </div>
        <div class="navbar-collapse collapse">

          <ul class="nav navbar-nav">
              <li><a href="{{ url_for('api_v1.get_jobs') }}">Jobs</a></li>
              <li><a href="{{ url_for('api_v1.get_results') }}">Results</a></li>
              <li><a href="{{ url_for('api_v1.get_testcases') }}">Testcases</a></li>
          </ul>

<!--         <div class="navbar-right">
             <input type="button" class="btn btn-default navbar-btn" value="Search" onclick="location.href='';">
         </div> -->

        </div><!--/.nav-collapse -->
      </div><!--/.container -->
    </div><!--/.navbar -->


    <div class="container">
    {% for message in get_flashed_messages() %}
      <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}
    </div>



    <div class="container">
    {% block body %}
       <h1> My First Flask Application! </h1>
    {% endblock %}
    </div>



    {% block footer %}
    {% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

resultsdb/templates/login.html
{% extends "layout.html" %}

{% from "_formhelpers.html" import form_field %}

{% block body %}

<div class="row">
<div class="col-md-4">
<form method="post" action="login">
    {{ form.csrf_token }}
    {{ form.next_page }}
    {{ form_field(form.username) }}
    {{ form_field(form.password) }}
    <input type="submit" class="btn btn-success" value="Login"/>
</form>
</div>
</div>

{% endblock %}